spring.application.name=MeetHub

# Configura\uFFFD\uFFFDes do DataSource
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Habilitar o Hibernate para criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Ativar o log de SQL para visualizar as queries executadas
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#security
spring.security.user.name=sa
spring.security.user.password=password
spring.h2.console.enable=true
spring.h2.console.path=/h2-console
logging.level.org.springframework.security=DEBUG

api.security.token.secret=${JWT_SECRET:my-secret-key}

configuration.key.emai=chave-secreta-confirmacao22

#email

# Configura\u00E7\u00F5es b\u00E1sicas

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=${SENDGRID_API_KEY}



# TLS e autentica\u00E7\u00E3o
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Charset padr\u00E3o (opcional, mas recomendado)
spring.mail.default-encoding=UTF-8

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
