CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CPF VARCHAR(11),
    PASSWORD VARCHAR(100) NOT NULL,
    COMPANYNAME VARCHAR(255) NOT NULL
);


CREATE TABLE ROOMS (
    ROOM_ID SERIAL PRIMARY KEY,
    name_room VARCHAR(255) NOT NULL,
    capacity VARCHAR(255) NOT NULL,
    place VARCHAR(255) NOT NULL,
    resources VARCHAR(255)
);

CREATE TABLE RESERVATIONS (
    RESERVATION_ID SERIAL PRIMARY KEY,
    person_name VARCHAR(255) NOT NULL,
    chosen_room VARCHAR(255) NOT NULL,
    date_time DATE NOT NULL,
    ROOM_ID INT NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    event_description VARCHAR(255),
    FOREIGN KEY (ROOM_ID) REFERENCES rooms(ROOM_ID)
);
